//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilesInfoClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFilesInfoService")]
    public interface IFilesInfoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilesInfoService/GetDiskDInfo", ReplyAction="http://tempuri.org/IFilesInfoService/GetDiskDInfoResponse")]
        System.IO.DriveInfo GetDiskDInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilesInfoService/GetDiskDInfo", ReplyAction="http://tempuri.org/IFilesInfoService/GetDiskDInfoResponse")]
        System.Threading.Tasks.Task<System.IO.DriveInfo> GetDiskDInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilesInfoService/GetFilesInfo", ReplyAction="http://tempuri.org/IFilesInfoService/GetFilesInfoResponse")]
        System.IO.DirectoryInfo GetFilesInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFilesInfoService/GetFilesInfo", ReplyAction="http://tempuri.org/IFilesInfoService/GetFilesInfoResponse")]
        System.Threading.Tasks.Task<System.IO.DirectoryInfo> GetFilesInfoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFilesInfoServiceChannel : FilesInfoClient.ServiceReference1.IFilesInfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FilesInfoServiceClient : System.ServiceModel.ClientBase<FilesInfoClient.ServiceReference1.IFilesInfoService>, FilesInfoClient.ServiceReference1.IFilesInfoService {
        
        public FilesInfoServiceClient() {
        }
        
        public FilesInfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FilesInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilesInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilesInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.DriveInfo GetDiskDInfo() {
            return base.Channel.GetDiskDInfo();
        }
        
        public System.Threading.Tasks.Task<System.IO.DriveInfo> GetDiskDInfoAsync() {
            return base.Channel.GetDiskDInfoAsync();
        }
        
        public System.IO.DirectoryInfo GetFilesInfo() {
            return base.Channel.GetFilesInfo();
        }
        
        public System.Threading.Tasks.Task<System.IO.DirectoryInfo> GetFilesInfoAsync() {
            return base.Channel.GetFilesInfoAsync();
        }
    }
}
